// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0vPhwIJhc9xJGYlmyZCHSZui2em3dcs4',
    appId: '1:223282184367:web:d11b8086c2be76f26ad45a',
    messagingSenderId: '223282184367',
    projectId: 'dumy-81353',
    authDomain: 'dumy-81353.firebaseapp.com',
    storageBucket: 'dumy-81353.appspot.com',
    measurementId: 'G-883MSPB2RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUdpG3B7bhckXiIRJb31pBqO6LQo0FEYk',
    appId: '1:223282184367:android:741d1e7677d10a9c6ad45a',
    messagingSenderId: '223282184367',
    projectId: 'dumy-81353',
    storageBucket: 'dumy-81353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7I4UJYkItLWzaXsMEikbKZ5dEZMihEMk',
    appId: '1:223282184367:ios:b8b9c76cbc749d4d6ad45a',
    messagingSenderId: '223282184367',
    projectId: 'dumy-81353',
    storageBucket: 'dumy-81353.appspot.com',
    iosBundleId: 'com.example.doctorBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7I4UJYkItLWzaXsMEikbKZ5dEZMihEMk',
    appId: '1:223282184367:ios:1015695f0e69e51b6ad45a',
    messagingSenderId: '223282184367',
    projectId: 'dumy-81353',
    storageBucket: 'dumy-81353.appspot.com',
    iosBundleId: 'com.example.doctorBooking.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9jsjJA8Q3l0graAJ5bTswW_pUB09oYSc',
    appId: '1:223282184367:web:2f94aa1c8fac01cc6ad45a',
    messagingSenderId: '223282184367',
    projectId: 'dumy-81353',
    authDomain: 'dumy-81353.firebaseapp.com',
    storageBucket: 'dumy-81353.firebasestorage.app',
    measurementId: 'G-JSFZ1FEVF1',
  );

}